### PR TITLE
note the 2MHz/2Msps requirement

### PR DESCRIPTION
**Pull request by ckuethe**

### CODE REVIEW

**Comment by ckuethe** [comment]
Yeah, that's what I was getting at. I now have a library of recordings in various sample rates, data formats, analog filter bandwidths; I have yet to fully characterize the minimum requirements for good detection/decoding.

**Comment by wnagele** [comment]
Thanks - can you rebase and squash those commits into a single one please?

**Comment by ckuethe** [comment]
updated diff

On Thu, Jul 9, 2015 at 4:22 AM, Wolfgang Nagele notifications@github.com
wrote:

> Thanks - can you rebase and squash those commits into a single one please?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/wnagele/gr-adsb/pull/2#issuecomment-119917550.

## 

GDB has a 'break' feature; why doesn't it have 'fix' too?

**Comment by wnagele** [comment]
Thanks!

**Pull request merged**
