### PR TITLE
add json format output

### PR DESCRIPTION
**Pull request by ckuethe**

### CODE REVIEW

**Comment by ckuethe** [comment]
I wanted to keep a fixed format to parallel the output of the CSV, which necessarily transports empty fields.

The example GRC uses a file input, and virtual sources/sinks to be a little bit easier to read. While we're discussing the examples, "flowgraph.grc" has both a hardware source and a throttle block which is not recommended.

**Comment by wnagele** [comment]
Ack on the JSON but JSON is different in that it supports fields existing or not - different from CSV. I think we should stick with the semantics of individual formats so implementations work better against it. For instance JSON libraries do not consider an empty string a missing value, whereas that's what we try to signal here.

On the flowgraph - could you just improve the existing one instead please? Also - please retain the licensing header in it.

**Comment by wnagele** [comment]
I've removed the throttle block from the flowgraph and also adjusted it to use Threshold instead of the multiply & add shifting of the signal. Will make it easier for entry level. Let's leave the virtual sinks out of it as the flowgraph is quite simple and easier for folks that are new to GNU Radio to grok without any of the virtual constructs.

**Comment by wnagele** [comment]
Thanks! :)

**Pull request merged**
